# Generated by Django 3.2.8 on 2021-10-31 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Co_So_Nganh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Co_So_Nhom_Nganh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mon_Chuyen_Nganh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mon_Dai_Cuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('MaMH', models.CharField(help_text='Mã môn học', max_length=10, primary_key=True, serialize=False)),
                ('TenMH', models.CharField(help_text='Mã số sinh viên.', max_length=150)),
                ('Khoa', models.CharField(choices=[('CNPM', 'Công nghệ phần mềm'), ('KTMT', 'Kỹ thuật máy tính'), ('KHMT', 'Khoa học máy tính'), ('HTTT', 'Hệ thống thông tin'), ('MMT&TT', 'Mạng máy tính và truyền thông'), ('KTTT', 'Khoa học và kỹ thuật thông tin')], default='CNPM', max_length=10)),
                ('NhomMH', models.CharField(choices=[('CNPM', 'Công nghệ phần mềm'), ('KTMT', 'Kỹ thuật máy tính'), ('KHMT', 'Khoa học máy tính'), ('HTTT', 'Hệ thống thông tin'), ('MMT&TT', 'Mạng máy tính và truyền thông'), ('KTTT', 'Khoa học và kỹ thuật thông tin')], default='DC', max_length=10)),
                ('MoTa', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('HoTen', models.CharField(help_text='Họ và tên của sinh viên.', max_length=30)),
                ('MSSV', models.CharField(help_text='Mã số sinh viên.', max_length=30, primary_key=True, serialize=False)),
                ('GioiTinh', models.CharField(choices=[('N', 'Nam'), ('F', 'Nữ')], default='N', max_length=1)),
                ('Email', models.EmailField(help_text='Địa chỉ email', max_length=200)),
                ('NgayDK', models.DateField(blank=True, null=True)),
                ('Khoa', models.CharField(choices=[('CNPM', 'Công nghệ phần mềm'), ('KTMT', 'Kỹ thuật máy tính'), ('KHMT', 'Khoa học máy tính'), ('HTTT', 'Hệ thống thông tin'), ('MMT&TT', 'Mạng máy tính và truyền thông'), ('KTTT', 'Khoa học và kỹ thuật thông tin')], default='CNPM', max_length=10)),
                ('MoTa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('MSSV', models.CharField(help_text='Họ và tên của sinh viên.', max_length=30, primary_key=True, serialize=False)),
                ('Password', models.CharField(help_text='Mã số sinh viên.', max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='TaiLieu',
            fields=[
                ('MaTL', models.CharField(help_text='Mã tài liệu', max_length=20, primary_key=True, serialize=False)),
                ('TenTL', models.CharField(help_text='Tên tài liệu.', max_length=150)),
                ('LoaiTL', models.CharField(choices=[('Slide', 'Slide bài giảng'), ('DT', 'Đề thi'), ('BT', 'Bài tập'), ('TLTK', 'Tài liệu tham khảo')], default='Slide', max_length=10)),
                ('MoTa', models.CharField(max_length=1000)),
                ('LuotTai', models.DecimalField(decimal_places=0, max_digits=5)),
                ('LuotXem', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Path', models.CharField(max_length=1000)),
                ('MaMH', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myproject.monhoc')),
            ],
        ),
        migrations.CreateModel(
            name='CommentTL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField(blank=True, null=True)),
                ('NoiDung', models.CharField(max_length=1000)),
                ('MSSV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.student')),
                ('MaTL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.tailieu')),
            ],
        ),
        migrations.CreateModel(
            name='CommentMH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateTimeField(blank=True, null=True)),
                ('NoiDung', models.CharField(max_length=1000)),
                ('MSSV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.student')),
                ('MaMH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.monhoc')),
            ],
        ),
    ]
