# Generated by Django 3.2.8 on 2021-10-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_alter_monhoc_nhommh'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailieu',
            name='TacGia',
            field=models.CharField(default=1, help_text='Họ và tên của tác giả.', max_length=30),
            preserve_default=False,
        ),
    ]
