# Generated by Django 3.2.8 on 2021-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_tailieu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailieu',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
