# Generated by Django 3.2.8 on 2021-11-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_tailieu_tacgia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailieu',
            name='LuotTai',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tailieu',
            name='LuotXem',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
