# Generated by Django 3.2.8 on 2021-11-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_auto_20211105_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmh',
            name='MaMH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myproject.monhoc'),
        ),
    ]
