# Generated by Django 3.2.8 on 2021-11-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0008_auto_20211103_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailieu',
            name='Path',
            field=models.FileField(upload_to=''),
        ),
    ]
