# Generated by Django 3.2.8 on 2021-11-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0013_auto_20211107_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailieu',
            name='KiemDuyet',
            field=models.BooleanField(default=False),
        ),
    ]
