# Generated by Django 3.2.8 on 2021-11-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0015_auto_20211107_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monhoc',
            name='Khoa',
            field=models.CharField(choices=[('CNPM', 'Công nghệ phần mềm'), ('KTMT', 'Kỹ thuật máy tính'), ('KHMT', 'Khoa học máy tính'), ('HTTT', 'Hệ thống thông tin'), ('MMT&TT', 'Mạng máy tính và truyền thông'), ('KTTT', 'Khoa học và kỹ thuật thông tin'), ('LLCT', 'Lý luận chính trị'), ('ToanTin', 'Toán - Tin học - KHTN'), ('NN', 'Ngoại ngữ'), ('K', 'Khác')], default='CNPM', max_length=10),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='NhomMH',
            field=models.CharField(choices=[('CNPM', 'Công nghệ phần mềm'), ('KTMT', 'Kỹ thuật máy tính'), ('KHMT', 'Khoa học máy tính'), ('HTTT', 'Hệ thống thông tin'), ('MMT&TT', 'Mạng máy tính và truyền thông'), ('KTTT', 'Khoa học và kỹ thuật thông tin'), ('LLCT', 'Lý luận chính trị'), ('ToanTin', 'Toán - Tin học - KHTN'), ('NN', 'Ngoại ngữ'), ('K', 'Khác')], default='DC', max_length=10),
        ),
    ]
