# Generated by Django 3.2.8 on 2021-11-07 05:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myproject', '0016_auto_20211107_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='commentmh',
            name='MSSV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commenttl',
            name='MSSV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='Khoa',
            field=models.CharField(choices=[('CNPM', 'Công nghệ phần mềm'), ('KTMT', 'Kỹ thuật máy tính'), ('KHMT', 'Khoa học máy tính'), ('HTTT', 'Hệ thống thông tin'), ('MMT&TT', 'Mạng máy tính và truyền thông'), ('KTTT', 'Khoa học và kỹ thuật thông tin'), ('LLCT', 'Lý luận chính trị'), ('ToanTin', 'Toán - Tin học - KHTN'), ('NN', 'Ngoại ngữ'), ('K', 'Khác')], default='K', max_length=10),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='MaMH',
            field=models.CharField(help_text='NT208', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='MoTa',
            field=models.CharField(help_text='Mô tả tổng quan về môn học, khối kiến thức sẽ được học...', max_length=1000),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='NhomMH',
            field=models.CharField(choices=[('CNPM', 'Công nghệ phần mềm'), ('KTMT', 'Kỹ thuật máy tính'), ('KHMT', 'Khoa học máy tính'), ('HTTT', 'Hệ thống thông tin'), ('MMT&TT', 'Mạng máy tính và truyền thông'), ('KTTT', 'Khoa học và kỹ thuật thông tin'), ('LLCT', 'Lý luận chính trị'), ('ToanTin', 'Toán - Tin học - KHTN'), ('NN', 'Ngoại ngữ'), ('K', 'Khác')], default='K', max_length=10),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='TenMH',
            field=models.CharField(help_text='Lập trình ứng dụng web', max_length=150),
        ),
        migrations.AlterField(
            model_name='tailieu',
            name='LoaiTL',
            field=models.CharField(choices=[('Slide', 'Slide bài giảng'), ('DT', 'Đề thi'), ('BT', 'Bài tập'), ('TLTK', 'Sách tham khảo')], default='Slide', max_length=10),
        ),
        migrations.AlterField(
            model_name='tailieu',
            name='MSSV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tailieu',
            name='MaTL',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tailieu',
            name='MoTa',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Thông tin về tài liệu', null=True),
        ),
        migrations.AlterField(
            model_name='tailieu',
            name='TacGia',
            field=models.CharField(help_text='Nguyễn Văn A', max_length=30),
        ),
        migrations.AlterField(
            model_name='tailieu',
            name='TenTL',
            field=models.CharField(help_text='Slide bài giảng lập trình ứng dụng web.', max_length=150),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
