# Generated by Django 3.2.8 on 2021-11-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0019_alter_tailieu_mssv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailieu',
            old_name='MSSV',
            new_name='username',
        ),
    ]
