# Generated by Django 3.2.8 on 2021-11-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0022_alter_fileupload_matl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='MaTL',
            field=models.CharField(max_length=30),
        ),
    ]
