# Generated by Django 3.2.8 on 2021-11-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0027_alter_monhoc_nhommh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monhoc',
            name='Khoa',
            field=models.CharField(choices=[('CongNghePhanMem', 'Công nghệ phần mềm'), ('KyThuatMayTinh', 'Kỹ thuật máy tính'), ('KhoaHocMayTinh', 'Khoa học máy tính'), ('HeThongThongTin', 'Hệ thống thông tin'), ('MangMayTinhTruyenThong', 'Mạng máy tính và truyền thông'), ('KyThuatThongTin', 'Khoa học và kỹ thuật thông tin'), ('LyLuanChinhTri', 'Lý luận chính trị'), ('ToanTinKHTN', 'Toán - Tin học - KHTN'), ('NgoaiNgu', 'Ngoại ngữ'), ('Khac', 'Khác')], default='Khac', max_length=30),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='NhomMH',
            field=models.CharField(choices=[('GiaoDucDaiCuong', 'Giáo dục đại cương'), ('CoSoNhomNganh', 'Cơ sở nhóm ngành'), ('CoSoNganh', 'Cơ sở ngành'), ('ChuyenNganh', 'Chuyên ngành'), ('Khac', 'Khác')], default='Khac', max_length=30),
        ),
    ]
