# Generated by Django 3.2.8 on 2021-11-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0033_auto_20211110_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='monhoc',
            name='SoLuongTL',
            field=models.IntegerField(default=0),
        ),
    ]
