# Generated by Django 3.2.8 on 2021-11-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0036_monhoc_tenmh_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monhoc',
            name='tenMH_search',
        ),
    ]
