# Generated by Django 3.2.8 on 2021-11-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0037_remove_monhoc_tenmh_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='monhoc',
            name='search',
            field=models.CharField(default='Lap trinh ung dung Web', max_length=150),
        ),
    ]
