# Generated by Django 3.2.8 on 2021-11-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0038_monhoc_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailieu',
            name='search',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='search',
            field=models.TextField(),
        ),
    ]
