# Generated by Django 3.2.8 on 2021-11-04 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_toan_tin_khtn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailieu',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
