# Generated by Django 3.2.8 on 2021-11-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_alter_tailieu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmh',
            name='NoiDung',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commenttl',
            name='NoiDung',
            field=models.TextField(),
        ),
    ]
