# Generated by Django 3.2.8 on 2021-11-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_auto_20211101_0822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='tailieu',
            name='MSSV',
            field=models.CharField(default=1, help_text='username người đăng', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentmh',
            name='MSSV',
            field=models.CharField(help_text='username người đăng', max_length=30),
        ),
        migrations.AlterField(
            model_name='commenttl',
            name='MSSV',
            field=models.CharField(help_text='username người đăng', max_length=30),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
