# Generated by Django 3.2.8 on 2021-11-03 11:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0005_auto_20211103_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailieu',
            name='MoTa',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
