# Generated by Django 3.2.8 on 2021-11-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_alter_monhoc_mota'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailieu',
            name='ThoiGian',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commentmh',
            name='NoiDung',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commenttl',
            name='NoiDung',
            field=models.TextField(),
        ),
    ]
