# Generated by Django 3.2.8 on 2021-11-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0006_alter_commentmh_mamh'),
        ('myproject', '0011_auto_20211104_1738'),
    ]

    operations = [
    ]
