# Generated by Django 3.2.8 on 2021-11-07 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0014_alter_tailieu_kiemduyet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('HoTen', models.CharField(help_text='Họ và tên của sinh viên.', max_length=30)),
                ('MSSV', models.CharField(help_text='Mã số sinh viên.', max_length=30, primary_key=True, serialize=False)),
                ('GioiTinh', models.CharField(choices=[('N', 'Nam'), ('F', 'Nữ')], default='N', max_length=1)),
                ('Email', models.EmailField(help_text='Địa chỉ email', max_length=200)),
                ('NgayDK', models.DateField(blank=True, null=True)),
                ('Khoa', models.CharField(choices=[('CNPM', 'Công nghệ phần mềm'), ('KTMT', 'Kỹ thuật máy tính'), ('KHMT', 'Khoa học máy tính'), ('HTTT', 'Hệ thống thông tin'), ('MMT&TT', 'Mạng máy tính và truyền thông'), ('KTTT', 'Khoa học và kỹ thuật thông tin')], default='CNPM', max_length=10)),
                ('MoTa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('MSSV', models.CharField(help_text='Họ và tên của sinh viên.', max_length=30, primary_key=True, serialize=False)),
                ('Password', models.CharField(help_text='Mã số sinh viên.', max_length=130)),
            ],
        ),
        migrations.DeleteModel(
            name='Co_So_Nganh',
        ),
        migrations.DeleteModel(
            name='Co_So_Nhom_Nganh',
        ),
        migrations.DeleteModel(
            name='Mon_Chuyen_Nganh',
        ),
        migrations.DeleteModel(
            name='Mon_Dai_Cuong',
        ),
        migrations.RenameField(
            model_name='tailieu',
            old_name='ThoiGian',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='commentmh',
            name='MaMH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myproject.monhoc'),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='Khoa',
            field=models.CharField(choices=[('CNPM', 'Công nghệ phần mềm'), ('KTMT', 'Kỹ thuật máy tính'), ('KHMT', 'Khoa học máy tính'), ('HTTT', 'Hệ thống thông tin'), ('MMT&TT', 'Mạng máy tính và truyền thông'), ('KTTT', 'Khoa học và kỹ thuật thông tin'), ('TT', 'Toan-Tin'), ('K', 'Khác')], default='CNPM', max_length=10),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='MoTa',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='monhoc',
            name='NhomMH',
            field=models.CharField(choices=[('CNPM', 'Công nghệ phần mềm'), ('KTMT', 'Kỹ thuật máy tính'), ('KHMT', 'Khoa học máy tính'), ('HTTT', 'Hệ thống thông tin'), ('MMT&TT', 'Mạng máy tính và truyền thông'), ('KTTT', 'Khoa học và kỹ thuật thông tin'), ('TT', 'Toan-Tin'), ('K', 'Khác')], default='DC', max_length=10),
        ),
        migrations.AlterField(
            model_name='commentmh',
            name='MSSV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.student'),
        ),
        migrations.AlterField(
            model_name='commenttl',
            name='MSSV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.student'),
        ),
    ]
