# Generated by Django 3.2.8 on 2021-11-07 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myproject', '0018_alter_tailieu_mssv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailieu',
            name='MSSV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
