# Generated by Django 3.2.8 on 2021-11-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0020_rename_mssv_tailieu_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmh',
            old_name='MSSV',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commenttl',
            old_name='MSSV',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tailieu',
            old_name='username',
            new_name='user',
        ),
    ]
