# Generated by Django 3.2.8 on 2021-11-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0021_auto_20211107_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='MaTL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.tailieu'),
        ),
    ]
