# Generated by Django 3.2.8 on 2021-11-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0023_alter_fileupload_matl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='id',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='Path',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
