# Generated by Django 3.2.8 on 2021-11-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0026_alter_fileupload_matl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monhoc',
            name='NhomMH',
            field=models.CharField(choices=[('GDDC', 'Giáo dục đại cương'), ('CSNN', 'Cơ sở nhóm ngành'), ('CSN', 'Cơ sở ngành'), ('CN', 'Chuyên ngành'), ('K', 'Khác')], default='K', max_length=10),
        ),
    ]
