# Generated by Django 3.2.8 on 2021-11-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0029_auto_20211107_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailieu',
            name='LoaiTL',
            field=models.CharField(choices=[('Slide', 'Slide bài giảng'), ('DeThi', 'Đề thi'), ('BaiTap', 'Bài tập'), ('TaiLieuTK', 'Tài liệu tham khảo')], default='Slide', max_length=10),
        ),
    ]
