# Generated by Django 3.2.8 on 2021-11-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0031_informationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationuser',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informationuser',
            name='FullName',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
