# Generated by Django 3.2.8 on 2021-11-13 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0034_monhoc_soluongtl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmh',
            name='ThoiGian',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commenttl',
            name='ThoiGian',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
