# Generated by Django 3.2.8 on 2021-11-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0039_auto_20211119_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailieu',
            name='LoaiTL',
            field=models.CharField(choices=[('Slide', 'Slide'), ('DeThi', 'Đề thi'), ('BaiTap', 'Bài tập'), ('TaiLieuTK', 'Tài liệu tham khảo')], default='Slide', max_length=10),
        ),
    ]
