# Generated by Django 3.2.8 on 2021-11-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0036_alter_commentmh_mamh'),
        ('myproject', '0040_alter_tailieu_loaitl'),
    ]

    operations = [
    ]
