# Generated by Django 3.2.8 on 2021-11-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0044_rename_kiemduyet_thongbao_xem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttl',
            name='MaTL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myproject.tailieu'),
        ),
    ]
