# Generated by Django 3.2.8 on 2021-12-05 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myproject', '0046_auto_20211204_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmh',
            name='MaMH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.monhoc'),
        ),
        migrations.AlterField(
            model_name='commentmh',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commenttl',
            name='MaTL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.tailieu'),
        ),
        migrations.AlterField(
            model_name='commenttl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informationuser',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recentview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tailieu',
            name='MaMH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myproject.monhoc'),
        ),
        migrations.AlterField(
            model_name='thongbao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
