# Generated by Django 3.2.8 on 2021-12-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0048_alter_fileupload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='Path',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='filename',
            field=models.CharField(max_length=200),
        ),
    ]
