# Generated by Django 3.2.8 on 2021-10-31 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Ma', models.CharField(max_length=49)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Họ và tên của sinh viên.', max_length=30)),
                ('student_code', models.CharField(help_text='Mã số sinh viên', max_length=18)),
                ('gender', models.CharField(choices=[('N', 'Nam'), ('F', 'Nữ')], default='N', max_length=1)),
                ('birth_place', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TestApp.khoa')),
            ],
        ),
    ]
