# Generated by Django 3.2.8 on 2021-10-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
